version: "3"
services:
  db:
    env_file:
      - .env
    image: mysql:8.3
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: fiapstream
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - fiapstream

  rabbitmq:
    hostname: rabbitmq
    env_file:
      - .env
    image: rabbitmq:3-management
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - fiapstream
      - fiapstream-public

  producer:
    hostname: producer
    env_file:
      - .env
    image: lamarcke/fiapstream-producer:0.0.7
    restart: always
    environment:
      AWS_REGION: us-east-1
      RABBITMQ_HOST: rabbitmq
      DB_URL: "db:3306"
    depends_on:
      - rabbitmq
      - db
    networks:
      - fiapstream
      - fiapstream-public

  processador:
    env_file:
      - .env
    image: lamarcke/fiapstream-processador:0.0.13
    restart: always
    environment:
      AWS_REGION: us-east-1
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
      - db
    networks:
      - fiapstream

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - fiapstream-public

volumes:
  mysql:
  rabbitmq:

networks:
  fiapstream:
  fiapstream-public:
