version: "3"
services:
  db:
    env_file:
      - .env
    image: mysql:8.3
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: fiapstream
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - fiapstream
    ports:
      - "3306:3306"

  rabbitmq:
    env_file:
      - .env
    image: rabbitmq:3-management
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fiapstream

  producer:
    env_file:
      - .env
    image: lamarcke/fiapstream-producer
    restart: always
    ports:
      - "8080:8080"
      - "8084:8084"
    environment:
      DB_URL: "db:3306"
      S3_ENDPOINT: "https://s3.amazonaws.com/"
    networks:
      - fiapstream

  processor:
    env_file:
      - .env
    image: lamarcke/fiapstream-processador
    restart: always
    networks:
      - fiapstream

volumes:
  mysql:
  rabbitmq:
  minio:

networks:
  fiapstream: