version: "3"
services:
  db:
    env_file:
      - .env
    image: mysql:8.3
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: fiapstream
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - fiapstream
    ports:
      - "3306:3306"

  rabbitmq:
    hostname: rabbitmq
    env_file:
      - .env
    image: rabbitmq:3-management
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fiapstream

  producer:
    env_file:
      - .env
    image: lamarcke/fiapstream-producer
    restart: always
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      DB_URL: "db:3306"
    depends_on:
      - rabbitmq
      - db
    networks:
      - fiapstream

  processador:
    env_file:
      - .env
    image: lamarcke/fiapstream-processador
    restart: always
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
      - db
    networks:
      - fiapstream

volumes:
  mysql:
  rabbitmq:

networks:
  fiapstream:
